# kubernetes-fastapi LoadBalancer Service
# Enables the pods in a deployment to be accessible from outside the cluster
apiVersion: v1
kind: Service
metadata:
  name: fast-api-svc
spec:
  selector:
    app: fast-api-sample
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: ClusterIP

---
# kf-api Deployment
# Defines the deployment of the app running in a pod on any worker node
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fast-api-sample
  labels:
    app: fast-api-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fast-api-sample
  template:
    metadata:
      labels:
        app: fast-api-sample
    spec:
      containers:
        - name: fast-api-sample
          image: "taethniacr.azurecr.io/fast-api-sample"
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          resources:
            # You must specify requests for CPU to autoscale
            # based on CPU utilization
            requests:
              cpu: "250m"
