apiVersion : apps/v1
kind: Deployment
metadata:
  name: "kubernetes-a94b"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "kubernetes-a94b"
  template:
    metadata:
      labels:
        app: "kubernetes-a94b"
    spec:
      containers:
        - name: "kubernetes-a94b"
          image: "taethniacr.azurecr.io/kubernetes"
          ports:
          - containerPort: 8080