apiVersion: v1
kind: Service
metadata:
    name: "kubernetes-a94b"
    labels:
        app: "kubernetes-a94b"
spec:
    type: LoadBalancer
    ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
    selector:
        app: "kubernetes-a94b"